params = {"FLIP_PROB_DECAY": 0.5,
            "GPR_BATCH_SIZE": 3000,
            "GPR_DEBUG": True,
            "GPR_EPS": 0.001,
            "GPR_EPSILON": 1e-06,
            "GPR_LEARNING_RATE": 0.01,
            "GPR_LENGTH_SCALE": 2.0,
            "GPR_MAGNITUDE": 1.0,
            "GPR_MAX_ITER": 500,
            "GPR_MAX_TRAIN_SIZE": 10000,
            "GPR_MU_MULTIPLIER": 1.0,
            "GPR_MODEL_NAME": "BasicGP",
            "GPR_HP_LEARNING_RATE": 0.001,
            "GPR_HP_MAX_ITER": 5000,
            "GPR_RIDGE": 1.0,
            "GPR_SIGMA_MULTIPLIER": 1.0,
            "GPR_UCB_SCALE": 0.2,
            "GPR_USE_GPFLOW": True,
            "GPR_UCB_BETA": "get_beta_td",
            "IMPORTANT_KNOB_NUMBER": 10000,
            "INIT_FLIP_PROB": 0.3,
            "NUM_SAMPLES": 10000,
            "TF_NUM_THREADS": 4,
            "TOP_NUM_CONFIG": 10,
            "ALPHA" : 1e-10,
            }